@HOST_URL = http://localhost:5000
@AUTH_ENDPOINT = http://localhost:5000/api/auth

### Register a user
POST {{AUTH_ENDPOINT}}/register
Content-Type: application/json

{
  "fullName": "Peter Parker",
  "email": "app.admin@example.com",
  "password": "P@ssw0rD",
  "bankName": "Canara Bank",
  "ifsc": "CAN0000023",
  "bankAccNum": "345678901234",
  "pan": "CDEFG3456H"
}

### Login a user
POST {{AUTH_ENDPOINT}}/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "P@ssw0rd"
}