export const DB_ERROR_CODES = {
  UNKNOWN_DB_ERROR: 'DB1000',
  UNKNOWN_ORM_ERROR: 'DB1001',
  COLUMN_VALUE_DATATYPE_MISMATCH: 'DB1002',
  UNIQUE_CONSTRAINT_VIOLATION: 'DB1003',
  WHERE_CONDITION_DOES_NOT_EXIST: 'DB1004',
  FOREIGN_KEY_CONSTRAINT_FAILURE: 'DB1005',
  NO_RELATED_RECORDS: 'DB1006',
  RELATIONS_NOT_CONNECTED: 'DB1007',
  CONNECTED_RECORDS_NOT_FOUND: 'DB1008',
  RECORD_DOES_NOT_EXIST: 'DB1009',
  INVALID_VALUE: 'DB1010',
};

export const SERVICE_ERROR_CODES = {
  UNKNOWN_SERVICE_ERROR: 'SE2000',
  INTERNAL_DB_ERROR: 'SE2001',
  ASSET_EXISTS: 'SE2002',
  INVALID_DB_RECORD_VALUE: 'SE2003',
  ASSEST_DOES_NOT_EXIST: 'SE2004',
  PASSWORD_NO_MATCH: 'SE2005',
  RELATED_RECORD_KEY_ERROR: 'SE2006',
  FILE_UPLOAD_TO_CLOUD_FAILED: 'SE2007',
  FILE_FETCH_FROM_CLOUD_FAILED: 'SE2008',
};

export const AWS_CLIENT_ERROR_CODES = {
  UNKNOWN_AWS_CLIENT_ERROR: 'AWS3000',
  S3_CLIENT_PUT_ERR: 'AWS3001',
  S3_CLIENT_GET_ERR: 'AWS3002',
  S3_CLIENT_DEL_ERR: 'AWS3003',
};

export const FILE_UPLOAD_ERROR_CODES = {
  UNKNOWN_FILE_UPLOAD_ERROR: 'FU4000',
  ALLOWED_MIMETYPE_MISMATCH: 'FU4001',
  FILE_TOO_LARGE: 'FU4002',
  TOO_MANY_FILES: 'FU4003',
};
